#!/usr/bin/env python3
"""Robustness checks for the Gaia DR3 open-cluster population break.

This script consumes the reproducible tables already generated by
``fossil_angular_momentum.py`` and ``scheme_v3_analysis.py``.  It does not
invent new kinematic measurements; all tests refit the population models after
resampling or filtering existing fitted clusters.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib

matplotlib.use("Agg")

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.stats import spearmanr

from scheme_v3_analysis import (
    broken_powerlaw_prediction,
    fit_broken_powerlaw,
    fit_single_powerlaw,
    model_comparison_v3,
)


def valid_population(df: pd.DataFrame) -> pd.DataFrame:
    ok = (
        np.isfinite(df["age_Myr"])
        & np.isfinite(df["logit_f_L"])
        & np.isfinite(df["logit_f_L_err"])
        & np.isfinite(df["f_L_v2"])
    )
    return df.loc[ok].copy().reset_index(drop=True)


def refit_summary(df: pd.DataFrame, label: str, comment: str = "") -> dict[str, float | str | int]:
    if len(df) < 12:
        return {
            "test": label,
            "n": int(len(df)),
            "break_age_Myr": np.nan,
            "delta_bic_vs_single": np.nan,
            "single_bic": np.nan,
            "broken_bic": np.nan,
            "sigma_int_single": np.nan,
            "sigma_int_broken": np.nan,
            "broken_preferred": False,
            "broken_delta_bic_lt_minus2": False,
            "broken_delta_bic_lt_minus6": False,
            "t_break_40_100_Myr": False,
            "break_hit_lower_bound": False,
            "break_hit_upper_bound": False,
            "status": "too_few_clusters",
            "comment": comment,
        }
    try:
        single = fit_single_powerlaw(df)
        broken = fit_broken_powerlaw(df)
        tb = float(np.exp(broken["params"][3]))
        delta = float(broken["bic"] - single["bic"])
        return {
            "test": label,
            "n": int(len(df)),
            "break_age_Myr": tb,
            "delta_bic_vs_single": delta,
            "single_bic": float(single["bic"]),
            "broken_bic": float(broken["bic"]),
            "sigma_int_single": float(single["sigma_int"]),
            "sigma_int_broken": float(broken["sigma_int"]),
            "broken_preferred": bool(delta < 0.0),
            "broken_delta_bic_lt_minus2": bool(delta < -2.0),
            "broken_delta_bic_lt_minus6": bool(delta < -6.0),
            "t_break_40_100_Myr": bool(40.0 <= tb <= 100.0),
            "break_hit_lower_bound": bool(tb <= 20.01),
            "break_hit_upper_bound": bool(tb >= 999.0),
            "status": "ok" if single["success"] and broken["success"] else "optimizer_warning",
            "comment": comment,
        }
    except Exception as exc:
        return {
            "test": label,
            "n": int(len(df)),
            "break_age_Myr": np.nan,
            "delta_bic_vs_single": np.nan,
            "single_bic": np.nan,
            "broken_bic": np.nan,
            "sigma_int_single": np.nan,
            "sigma_int_broken": np.nan,
            "broken_preferred": False,
            "broken_delta_bic_lt_minus2": False,
            "broken_delta_bic_lt_minus6": False,
            "t_break_40_100_Myr": False,
            "break_hit_lower_bound": False,
            "break_hit_upper_bound": False,
            "status": f"failed:{type(exc).__name__}",
            "comment": comment,
        }


def selection_tests(df: pd.DataFrame) -> pd.DataFrame:
    tests: list[tuple[str, pd.Series, str]] = []
    tests.append(("all_fitted", pd.Series(True, index=df.index), "all fitted clusters"))
    if "p_good_v3" in df:
        tests.append(("p_good_gt_0p7", df["p_good_v3"] > 0.7, "posterior good probability cut"))
    if "n_RV_fit" in df:
        tests.append(("n_rv_fit_ge_75", df["n_RV_fit"] >= 75, "higher internal-RV threshold"))
        tests.append(("n_rv_fit_ge_100", df["n_RV_fit"] >= 100, "strict internal-RV threshold"))
    if "N_catalog" in df:
        tests.append(("n_catalog_ge_500", df["N_catalog"] >= 500, "higher catalog membership"))
    if "age_Myr" in df:
        tests.append(("exclude_age_lt_30", df["age_Myr"] >= 30.0, "remove very young clusters"))
    if "MassJ_Msun" in df:
        q10, q90 = df["MassJ_Msun"].quantile([0.10, 0.90])
        tests.append(("exclude_mass_extremes", df["MassJ_Msun"].between(q10, q90), "drop mass deciles"))
    if "rJpc" in df:
        q10, q90 = df["rJpc"].quantile([0.10, 0.90])
        tests.append(("exclude_radius_extremes", df["rJpc"].between(q10, q90), "drop radius deciles"))
    if "R_GC_kpc" in df:
        tests.append(("nearby_rgc_7_to_9p5", df["R_GC_kpc"].between(7.0, 9.5), "near solar circle"))

    rows = [refit_summary(df.loc[mask].copy(), label, comment) for label, mask, comment in tests]
    return pd.DataFrame(rows)


def bootstrap_breaks(df: pd.DataFrame, n_boot: int, rng: np.random.Generator) -> pd.DataFrame:
    rows = []
    n = len(df)
    for i in range(n_boot):
        idx = rng.integers(0, n, n)
        sub = df.iloc[idx].copy().reset_index(drop=True)
        row = refit_summary(sub, f"bootstrap_{i:04d}")
        row["iteration"] = i
        rows.append(row)
    return pd.DataFrame(rows)


def bootstrap_model_selection_summary(bootstrap: pd.DataFrame) -> pd.DataFrame:
    ok = bootstrap["status"].eq("ok") & np.isfinite(bootstrap["break_age_Myr"]) & np.isfinite(bootstrap["delta_bic_vs_single"])
    sub = bootstrap.loc[ok].copy()
    if sub.empty:
        return pd.DataFrame(
            [
                {
                    "n_success": 0,
                    "n_total": int(len(bootstrap)),
                    "broken_preferred_fraction": np.nan,
                    "broken_delta_bic_lt_minus2_fraction": np.nan,
                    "broken_delta_bic_lt_minus6_fraction": np.nan,
                    "t_break_40_100_Myr_fraction": np.nan,
                    "break_hit_lower_bound_fraction": np.nan,
                    "break_hit_upper_bound_fraction": np.nan,
                }
            ]
        )
    return pd.DataFrame(
        [
            {
                "n_success": int(len(sub)),
                "n_total": int(len(bootstrap)),
                "broken_preferred_fraction": float(sub["broken_preferred"].mean()),
                "broken_delta_bic_lt_minus2_fraction": float(sub["broken_delta_bic_lt_minus2"].mean()),
                "broken_delta_bic_lt_minus6_fraction": float(sub["broken_delta_bic_lt_minus6"].mean()),
                "t_break_40_100_Myr_fraction": float(sub["t_break_40_100_Myr"].mean()),
                "break_hit_lower_bound_fraction": float(sub["break_hit_lower_bound"].mean()),
                "break_hit_upper_bound_fraction": float(sub["break_hit_upper_bound"].mean()),
                "median_delta_bic_vs_single": float(sub["delta_bic_vs_single"].median()),
                "p16_delta_bic_vs_single": float(np.percentile(sub["delta_bic_vs_single"], 16)),
                "p84_delta_bic_vs_single": float(np.percentile(sub["delta_bic_vs_single"], 84)),
                "median_t_break_Myr": float(sub["break_age_Myr"].median()),
                "p16_t_break_Myr": float(np.percentile(sub["break_age_Myr"], 16)),
                "p84_t_break_Myr": float(np.percentile(sub["break_age_Myr"], 84)),
            }
        ]
    )


def jackknife_breaks(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    for i, row in df.reset_index(drop=True).iterrows():
        sub = df.drop(df.index[i]).copy().reset_index(drop=True)
        out = refit_summary(sub, str(row.get("Name", i)), "leave-one-out")
        out["left_out_name"] = row.get("Name", "")
        out["left_out_id"] = row.get("ID", np.nan)
        out["left_out_age_Myr"] = row.get("age_Myr", np.nan)
        out["left_out_f_L"] = row.get("f_L_v2", np.nan)
        rows.append(out)
    return pd.DataFrame(rows)


def age_uncertainty_tests(
    df: pd.DataFrame,
    sigmas: list[float],
    n_mc: int,
    rng: np.random.Generator,
) -> pd.DataFrame:
    rows = []
    if {"logAge16", "logAge84"}.issubset(df.columns):
        cat_sigma = 0.5 * (df["logAge84"].to_numpy(float) - df["logAge16"].to_numpy(float))
        cat_sigma = np.where(np.isfinite(cat_sigma) & (cat_sigma > 0), cat_sigma, np.nan)
        sigmas = [-1.0, *sigmas]
    else:
        cat_sigma = np.full(len(df), np.nan)

    for sigma in sigmas:
        label = "catalog_logage_uncertainty" if sigma < 0 else f"assumed_sigma_logage_{sigma:.2f}"
        use_sigma = cat_sigma if sigma < 0 else np.full(len(df), sigma)
        if not np.isfinite(use_sigma).any():
            rows.append(refit_summary(df.iloc[0:0], label, "age uncertainty unavailable"))
            continue
        for i in range(n_mc):
            sub = df.copy()
            log_age = np.log10(sub["age_Myr"].to_numpy(float)) + rng.normal(0.0, use_sigma)
            sub["age_Myr"] = np.clip(10**log_age, 1.0, 5000.0)
            row = refit_summary(sub, label)
            row["iteration"] = i
            row["sigma_log_age"] = sigma
            rows.append(row)
    return pd.DataFrame(rows)


def residual_diagnostics(df: pd.DataFrame) -> pd.DataFrame:
    fit = fit_broken_powerlaw(df)
    pred = broken_powerlaw_prediction(fit["params"], df["age_Myr"].to_numpy(float))
    residual = df["logit_f_L"].to_numpy(float) - pred
    rows = []
    candidates = [
        "age_Myr",
        "MassJ_Msun",
        "rJpc",
        "r_h_pc",
        "R_GC_kpc",
        "n_RV_fit",
        "N_catalog",
        "sigma1d_kms",
        "probJ",
        "f_L_null_p",
    ]
    for col in candidates:
        if col not in df:
            continue
        x = df[col].to_numpy(float)
        ok = np.isfinite(x) & np.isfinite(residual)
        if ok.sum() < 8:
            continue
        rho, p_value = spearmanr(x[ok], residual[ok])
        rows.append(
            {
                "property": col,
                "n": int(ok.sum()),
                "spearman_rho": float(rho),
                "p_value": float(p_value),
            }
        )
    return pd.DataFrame(rows).sort_values("p_value")


def null_shuffle_summary(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    if "f_L_null_p" not in df:
        return pd.DataFrame(rows)
    p = df["f_L_null_p"].to_numpy(float)
    finite = p[np.isfinite(p)]
    if len(finite):
        rows.append(
            {
                "metric": "all_fitted",
                "n": int(len(finite)),
                "median_null_p": float(np.median(finite)),
                "false_positive_fraction_p_lt_0p05": float(np.mean(finite < 0.05)),
                "false_positive_fraction_p_lt_0p10": float(np.mean(finite < 0.10)),
            }
        )
    if "p_good_v3" in df:
        clean = df["p_good_v3"] > 0.7
        finite = df.loc[clean, "f_L_null_p"].to_numpy(float)
        finite = finite[np.isfinite(finite)]
        if len(finite):
            rows.append(
                {
                    "metric": "p_good_gt_0p7",
                    "n": int(len(finite)),
                    "median_null_p": float(np.median(finite)),
                    "false_positive_fraction_p_lt_0p05": float(np.mean(finite < 0.05)),
                    "false_positive_fraction_p_lt_0p10": float(np.mean(finite < 0.10)),
                }
            )
    return pd.DataFrame(rows)


def systematics_amplitudes(df: pd.DataFrame) -> pd.DataFrame:
    rows = []
    omega = df["omega_mag_Myr_inv"].to_numpy(float) if "omega_mag_Myr_inv" in df else np.array([])
    if len(omega):
        finite = omega[np.isfinite(omega) & (omega > 0)]
        if len(finite):
            # Flat-rotation Oort shear near the Sun: A ~= 15 km/s/kpc.
            # 1 km/s/kpc = 0.0010227 Myr^-1.
            oort_a_myr = 15.0 * 1e-3 * 1.0227121650537077
            rows.append(
                {
                    "systematic": "local_galactic_shear_oort_A",
                    "amplitude_Myr_inv": oort_a_myr,
                    "median_measured_omega_Myr_inv": float(np.median(finite)),
                    "median_amplitude_over_omega": float(np.median(oort_a_myr / finite)),
                    "comment": "order-of-magnitude Oort A comparison only",
                }
            )
    if {"rJpc", "dist50", "RV"}.issubset(df.columns):
        perspective = np.abs(df["RV"].to_numpy(float)) * df["rJpc"].to_numpy(float) / np.maximum(df["dist50"].to_numpy(float), 1.0)
        perspective_myr = perspective * 1.0227121650537077 / np.maximum(df["rJpc"].to_numpy(float), 1e-6)
        finite = perspective_myr[np.isfinite(perspective_myr) & (perspective_myr > 0)]
        measured = df["omega_mag_Myr_inv"].to_numpy(float) if "omega_mag_Myr_inv" in df else np.full(len(df), np.nan)
        ok = np.isfinite(perspective_myr) & np.isfinite(measured) & (measured > 0)
        if len(finite):
            rows.append(
                {
                    "systematic": "perspective_expansion_upper_scale",
                    "amplitude_Myr_inv": float(np.median(finite)),
                    "median_measured_omega_Myr_inv": float(np.nanmedian(measured)),
                    "median_amplitude_over_omega": float(np.median(perspective_myr[ok] / measured[ok])) if ok.any() else np.nan,
                    "comment": "radial-motion gradient scale, not subtracted from antisymmetric omega",
                }
            )
    return pd.DataFrame(rows)


def naive_vs_conservative_table(
    formal_path: Path,
    intrinsic: pd.DataFrame,
    selection: pd.DataFrame,
    bootstrap_summary: pd.DataFrame,
) -> pd.DataFrame:
    rows = []
    if formal_path.exists():
        formal = pd.read_csv(formal_path)
        broken = formal.loc[formal["model"] == "broken"].iloc[0]
        single = formal.loc[formal["model"] == "single"].iloc[0]
        preferred = formal.sort_values("bic").iloc[0]["model"]
        rows.append(
            {
                "model_assumption": "formal_error_only",
                "preferred_model": preferred,
                "delta_bic_broken_vs_single": float(broken["bic"] - single["bic"]),
                "t_break_Myr": float(broken["break_age_Myr"]),
                "interpretation": "naive fit favors broken model; retained as reproducible contrast",
            }
        )
    else:
        rows.append(
            {
                "model_assumption": "formal_error_only",
                "preferred_model": "TODO",
                "delta_bic_broken_vs_single": np.nan,
                "t_break_Myr": np.nan,
                "interpretation": "TODO: previous no-intrinsic-scatter output unavailable",
            }
        )

    intrinsic_broken = intrinsic.loc[intrinsic["model"] == "broken"].iloc[0]
    intrinsic_best = intrinsic.sort_values("bic").iloc[0]["model"]
    rows.append(
        {
            "model_assumption": "intrinsic_scatter_all_fitted",
            "preferred_model": intrinsic_best,
            "delta_bic_broken_vs_single": float(intrinsic_broken["delta_bic_vs_single"]),
            "t_break_Myr": float(intrinsic_broken["break_age_Myr"]),
            "interpretation": "age-only break not required after fitting population scatter",
        }
    )

    clean = selection.loc[selection["test"] == "p_good_gt_0p7"].iloc[0]
    rows.append(
        {
            "model_assumption": "intrinsic_scatter_cleaned_sample",
            "preferred_model": "single" if clean["delta_bic_vs_single"] >= 0 else "broken",
            "delta_bic_broken_vs_single": float(clean["delta_bic_vs_single"]),
            "t_break_Myr": float(clean["break_age_Myr"]),
            "interpretation": "cleaned sample also does not require the break",
        }
    )

    boot = bootstrap_summary.iloc[0]
    rows.append(
        {
            "model_assumption": "bootstrap_cleaned_sample",
            "preferred_model": "single_dominant",
            "delta_bic_broken_vs_single": float(boot["median_delta_bic_vs_single"]),
            "t_break_Myr": float(boot["median_t_break_Myr"]),
            "interpretation": (
                f"broken preferred in {100.0 * boot['broken_preferred_fraction']:.1f}% of successful resamples"
            ),
        }
    )
    return pd.DataFrame(rows)


def systematics_budget_table(
    selection: pd.DataFrame,
    age_mc: pd.DataFrame,
    residuals: pd.DataFrame,
    nulls: pd.DataFrame,
    systematics: pd.DataFrame,
) -> pd.DataFrame:
    def selection_row(test: str) -> pd.Series:
        hit = selection.loc[selection["test"] == test]
        return hit.iloc[0] if len(hit) else pd.Series(dtype=object)

    age_ok = age_mc["status"].eq("ok") & np.isfinite(age_mc["break_age_Myr"])
    age_values = age_mc.loc[age_ok, "break_age_Myr"].to_numpy(float)
    nrv = selection_row("n_rv_fit_ge_75")
    members = selection_row("n_catalog_ge_500")
    mass = selection_row("exclude_mass_extremes")
    radius = selection_row("exclude_radius_extremes")
    null_row = nulls.loc[nulls["metric"] == "p_good_gt_0p7"].iloc[0] if not nulls.empty and (nulls["metric"] == "p_good_gt_0p7").any() else None

    rows = [
        {
            "source": "intrinsic scatter",
            "diagnostic": "sigma_int about 3 in logit space",
            "direction_of_effect": "absorbs cluster-to-cluster diversity; removes BIC need for broken model",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "age uncertainty",
            "diagnostic": f"MC median t_b spans {np.nanmin(age_values):.1f}-{np.nanmax(age_values):.1f} Myr" if len(age_values) else "unavailable",
            "direction_of_effect": "moves conditional break over tens to hundreds of Myr",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "Gaia RV selection",
            "diagnostic": f"N_RV>=75 gives t_b={float(nrv.break_age_Myr):.1f} Myr, Delta BIC={float(nrv.delta_bic_vs_single):.1f}" if len(nrv) else "unavailable",
            "direction_of_effect": "changes conditional age but not BIC preference",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "membership count",
            "diagnostic": f"N_catalog>=500 gives t_b={float(members.break_age_Myr):.1f} Myr, Delta BIC={float(members.delta_bic_vs_single):.1f}" if len(members) else "unavailable",
            "direction_of_effect": "can push break to upper bound",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "velocity-shuffle null probability",
            "diagnostic": f"clean median p_null={float(null_row.median_null_p):.3f}; p<0.05 fraction={float(null_row.false_positive_fraction_p_lt_0p05):.3f}" if null_row is not None else "unavailable",
            "direction_of_effect": "residuals correlate with null probability",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "mass cuts",
            "diagnostic": f"drop deciles gives t_b={float(mass.break_age_Myr):.1f} Myr, Delta BIC={float(mass.delta_bic_vs_single):.1f}" if len(mass) else "unavailable",
            "direction_of_effect": "conditional age shifts",
            "can_create_robust_70Myr_clock": "no",
        },
        {
            "source": "radius cuts",
            "diagnostic": f"drop deciles gives t_b={float(radius.break_age_Myr):.1f} Myr, Delta BIC={float(radius.delta_bic_vs_single):.1f}" if len(radius) else "unavailable",
            "direction_of_effect": "conditional age shifts",
            "can_create_robust_70Myr_clock": "no",
        },
    ]
    for name in ["local_galactic_shear_oort_A", "perspective_expansion_upper_scale"]:
        hit = systematics.loc[systematics["systematic"] == name]
        if len(hit):
            row = hit.iloc[0]
            rows.append(
                {
                    "source": name,
                    "diagnostic": f"median amplitude/omega={float(row['median_amplitude_over_omega']):.3f}",
                    "direction_of_effect": row["comment"],
                    "can_create_robust_70Myr_clock": "no",
                }
            )
    return pd.DataFrame(rows)


def make_robustness_figure(
    bootstrap: pd.DataFrame,
    selection: pd.DataFrame,
    age_mc: pd.DataFrame,
    residuals: pd.DataFrame,
    outdir: Path,
) -> None:
    fig, axes = plt.subplots(2, 2, figsize=(10.5, 8.0), constrained_layout=True)

    ax = axes[0, 0]
    ok_boot = bootstrap["status"].eq("ok") & np.isfinite(bootstrap["break_age_Myr"])
    ax.hist(bootstrap.loc[ok_boot, "break_age_Myr"], bins=30, color="darkorange", alpha=0.82)
    ax.set_xlabel(r"Bootstrap $t_b$ (Myr)")
    ax.set_ylabel("Resamples")

    ax = axes[0, 1]
    ok_sel = selection["status"].eq("ok")
    y = np.arange(ok_sel.sum())
    rows = selection.loc[ok_sel].sort_values("break_age_Myr")
    ax.errorbar(rows["break_age_Myr"], y, fmt="o", color="steelblue")
    ax.set_yticks(y)
    ax.set_yticklabels(rows["test"], fontsize=8)
    ax.set_xlabel(r"Selection-test $t_b$ (Myr)")

    ax = axes[1, 0]
    ok_age = age_mc["status"].eq("ok") & np.isfinite(age_mc["break_age_Myr"])
    labels = list(dict.fromkeys(age_mc.loc[ok_age, "test"].astype(str)))
    data = [age_mc.loc[ok_age & age_mc["test"].eq(label), "break_age_Myr"].to_numpy(float) for label in labels]
    ax.boxplot(data, tick_labels=[label.replace("assumed_sigma_logage_", "sig=") for label in labels], vert=True)
    ax.tick_params(axis="x", rotation=35, labelsize=8)
    ax.set_ylabel(r"Age-MC $t_b$ (Myr)")

    ax = axes[1, 1]
    rows = residuals.head(8)
    ax.barh(np.arange(len(rows)), rows["spearman_rho"], color="0.45")
    ax.set_yticks(np.arange(len(rows)))
    ax.set_yticklabels(rows["property"], fontsize=8)
    ax.axvline(0.0, color="black", lw=1.0)
    ax.set_xlabel("Residual Spearman rho")
    ax.invert_yaxis()

    fig.savefig(outdir / "figure_robustness_checks.png", dpi=240)
    plt.close(fig)


def write_summary(
    selection: pd.DataFrame,
    bootstrap: pd.DataFrame,
    jackknife: pd.DataFrame,
    age_mc: pd.DataFrame,
    residuals: pd.DataFrame,
    nulls: pd.DataFrame,
    systematics: pd.DataFrame,
    bootstrap_selection: pd.DataFrame,
    outdir: Path,
) -> None:
    boot_ok = bootstrap["status"].eq("ok") & np.isfinite(bootstrap["break_age_Myr"])
    boot_tb = bootstrap.loc[boot_ok, "break_age_Myr"].to_numpy(float)
    jack_ok = jackknife["status"].eq("ok") & np.isfinite(jackknife["break_age_Myr"])
    jack_tb = jackknife.loc[jack_ok, "break_age_Myr"].to_numpy(float)
    age_ok = age_mc["status"].eq("ok") & np.isfinite(age_mc["break_age_Myr"])

    lines = [
        "# Robustness Checks",
        "",
        "## Bootstrap",
        "",
        f"Successful resamples: {len(boot_tb)} / {len(bootstrap)}",
        f"t_b median and 16-84% interval: {np.nanmedian(boot_tb):.2f} ({np.nanpercentile(boot_tb, 16):.2f}-{np.nanpercentile(boot_tb, 84):.2f}) Myr",
        f"Broken model preferred by BIC: {100.0 * bootstrap_selection['broken_preferred_fraction'].iloc[0]:.1f}%",
        f"Broken model strongly preferred (Delta BIC < -6): {100.0 * bootstrap_selection['broken_delta_bic_lt_minus6_fraction'].iloc[0]:.1f}%",
        "",
        "## Leave-one-out jackknife",
        "",
        f"Successful leave-one-out fits: {len(jack_tb)} / {len(jackknife)}",
        f"t_b range: {np.nanmin(jack_tb):.2f}-{np.nanmax(jack_tb):.2f} Myr",
        "",
        "## Selection tests",
        "",
    ]
    for row in selection.itertuples():
        lines.append(
            f"- {row.test}: n={row.n}, t_b={row.break_age_Myr:.2f} Myr, Delta BIC={row.delta_bic_vs_single:.2f}, status={row.status}"
        )
    lines.extend(["", "## Age uncertainty tests", ""])
    for label, sub in age_mc.loc[age_ok].groupby("test"):
        values = sub["break_age_Myr"].to_numpy(float)
        delta = sub["delta_bic_vs_single"].to_numpy(float)
        lines.append(
            f"- {label}: t_b={np.nanmedian(values):.2f} ({np.nanpercentile(values, 16):.2f}-{np.nanpercentile(values, 84):.2f}) Myr; "
            f"Delta BIC={np.nanmedian(delta):.2f}"
        )
    lines.extend(["", "## Residual diagnostics", ""])
    for row in residuals.head(6).itertuples():
        lines.append(f"- {row.property}: rho={row.spearman_rho:.3f}, p={row.p_value:.3g}, n={row.n}")
    lines.extend(["", "## Null-shuffle diagnostics", ""])
    if nulls.empty:
        lines.append("- No f_L_null_p column available.")
    else:
        for row in nulls.itertuples():
            lines.append(
                f"- {row.metric}: n={row.n}, median p_null={row.median_null_p:.3f}, "
                f"p<0.05 fraction={row.false_positive_fraction_p_lt_0p05:.3f}"
            )
    lines.extend(["", "## Systematics amplitude checks", ""])
    if systematics.empty:
        lines.append("- No amplitude checks available from current tables.")
    else:
        for row in systematics.itertuples():
            lines.append(
                f"- {row.systematic}: amplitude={row.amplitude_Myr_inv:.4g} Myr^-1, "
                f"median amplitude/omega={row.median_amplitude_over_omega:.3f}; {row.comment}"
            )
    (outdir / "summary.md").write_text("\n".join(lines) + "\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--population", type=Path, default=Path("outputs_v3/cluster_population.csv"))
    parser.add_argument("--sample", type=Path, default=Path("outputs/sample_selection.csv"))
    parser.add_argument("--outdir", type=Path, default=Path("outputs_robustness"))
    parser.add_argument("--bootstrap", type=int, default=300)
    parser.add_argument("--age-mc", type=int, default=80)
    parser.add_argument("--seed", type=int, default=20260624)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    args.outdir.mkdir(parents=True, exist_ok=True)
    rng = np.random.default_rng(args.seed)

    df = valid_population(pd.read_csv(args.population))
    if args.sample.exists():
        sample = pd.read_csv(args.sample)
        sample_cols = ["ID", "dist50", "RV", "logAge16", "logAge84"]
        df = df.merge(sample[[col for col in sample_cols if col in sample.columns]], on="ID", how="left")

    comparison, _ = model_comparison_v3(df)
    selection = selection_tests(df)
    clean = df[df.get("p_good_v3", pd.Series(1.0, index=df.index)) > 0.7].copy().reset_index(drop=True)
    bootstrap = bootstrap_breaks(clean, args.bootstrap, rng)
    bootstrap_selection = bootstrap_model_selection_summary(bootstrap)
    jackknife = jackknife_breaks(clean)
    age_mc = age_uncertainty_tests(clean, [0.05, 0.10, 0.15, 0.20], args.age_mc, rng)
    residuals = residual_diagnostics(clean)
    nulls = null_shuffle_summary(df)
    systematics = systematics_amplitudes(df)
    naive_vs_conservative = naive_vs_conservative_table(
        Path("outputs_v3_debug/model_comparison.csv"), comparison, selection, bootstrap_selection
    )
    budget = systematics_budget_table(selection, age_mc, residuals, nulls, systematics)

    comparison.to_csv(args.outdir / "intrinsic_scatter_model_comparison.csv", index=False)
    selection.to_csv(args.outdir / "selection_robustness.csv", index=False)
    bootstrap.to_csv(args.outdir / "bootstrap_breaks.csv", index=False)
    bootstrap_selection.to_csv(args.outdir / "bootstrap_model_selection_summary.csv", index=False)
    jackknife.to_csv(args.outdir / "jackknife_breaks.csv", index=False)
    age_mc.to_csv(args.outdir / "age_uncertainty_mc.csv", index=False)
    residuals.to_csv(args.outdir / "residual_diagnostics.csv", index=False)
    nulls.to_csv(args.outdir / "null_shuffle_summary.csv", index=False)
    systematics.to_csv(args.outdir / "systematics_amplitudes.csv", index=False)
    naive_vs_conservative.to_csv(args.outdir / "naive_vs_conservative.csv", index=False)
    budget.to_csv(args.outdir / "systematics_budget.csv", index=False)

    make_robustness_figure(bootstrap, selection, age_mc, residuals, args.outdir)
    write_summary(selection, bootstrap, jackknife, age_mc, residuals, nulls, systematics, bootstrap_selection, args.outdir)

    broken = comparison.loc[comparison["model"] == "broken"].iloc[0]
    boot_ok = bootstrap["status"].eq("ok") & np.isfinite(bootstrap["break_age_Myr"])
    print(f"Intrinsic-scatter broken Delta BIC vs single: {broken['delta_bic_vs_single']:.3f}")
    print(f"Intrinsic-scatter broken break: {broken['break_age_Myr']:.2f} Myr")
    print(f"Clean-sample bootstrap successes: {int(boot_ok.sum())}/{len(bootstrap)}")
    print(f"Wrote outputs to {args.outdir}")


if __name__ == "__main__":
    main()
